CC = gcc
CFLAGS = -Wall -Wextra -Werror -pedantic

all: 0-bubble_sort.o 0-main.o print_array.o
	$(CC) $(CFLAGS) -o 0-bubble_sort 0-bubble_sort.o 0-main.o print_array.o

0-bubble_sort.o: 0-bubble_sort.c
	$(CC) $(CFLAGS) -c 0-bubble_sort.c

0-main.o: 0-main.c
	$(CC) $(CFLAGS) -c 0-main.c

print_array.o: print_array.c
	$(CC) $(CFLAGS) -c print_array.c

clean:
	rm -f 0-bubble_sort 0-bubble_sort.o 0-main.o print_array.o